language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby
  - ree
script: "bundle exec rake spec:all"
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
notifications:
  email:
    recipients:
      - sbazyl@google.com
    on_success: change
    on_failure: change
matrix:
  allow_failures:
    - rvm: 2.0.0
