language: ruby
sudo: false
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - jruby
  - jruby-9.0.5.0
env:
  - RAILS_VERSION="~>4.2.0"
  - RAILS_VERSION="~>5.0.0"
matrix:
  exclude:
    - env: RAILS_VERSION="~>5.0.0"
      rvm: 2.0
    - env: RAILS_VERSION="~>5.0.0"
      rvm: 2.1
before_install: gem install bundler
notifications:
  email:
    recipients:
      - sbazyl@google.com
    on_success: change
    on_failure: change
