name: Weekly-Generate-Updates
on:
  schedule:
    - cron: '02 9 * * 0'

jobs:
  generate-updates:
    if: ${{ github.repository == 'googleapis/google-api-ruby-client' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.YOSHI_CODE_BOT_TOKEN }}
      APPROVAL_GITHUB_TOKEN: ${{secrets.YOSHI_APPROVER_TOKEN}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Ruby 3.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - name: Install tools
        run: "gem install --no-document toys"
      - name: Execute
        run: |
          toys generate-updates -v --fork --all --clean
